/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.nio.file.Files;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.NhanVien;
import services.KhachHangService;
import services.NhanVienService;
import utils.CustomRenderer;

import utils.XDate;
import utils.fileChoose;

public class NhanVienView extends javax.swing.JPanel {

    ArrayList<NhanVien> list = new ArrayList<>();
    int page = 1, index = 1;
    DefaultTableModel model = new DefaultTableModel();
    NhanVienService service = new NhanVienService();
    String ten = "", sdt = "";
    String path = "C:\\Users\\dovan\\OneDrive\\Desktop\\images\\nhanVien\\";
    String path1 = "";

    public NhanVienView() {
        initComponents();
        model = (DefaultTableModel) tblactive.getModel();
        loadDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        txt_dChi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rdoNu = new javax.swing.JRadioButton();
        rdoNam = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_nsinh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_ntao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_gchu = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_mk1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_mk2 = new javax.swing.JTextField();
        txt_anh = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rdoQL = new javax.swing.JRadioButton();
        rdoNV = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblactive = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        vitri = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        txt_tk = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Ngày tạo");

        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Họ và tên ");

        txt_ten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_ten.setForeground(new java.awt.Color(0, 0, 204));

        txt_dChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_dChi.setForeground(new java.awt.Color(0, 0, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Địa chỉ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Giới tính");

        buttonGroup1.add(rdoNu);
        rdoNu.setForeground(new java.awt.Color(0, 0, 204));
        rdoNu.setText("Nữ");

        buttonGroup1.add(rdoNam);
        rdoNam.setForeground(new java.awt.Color(0, 0, 204));
        rdoNam.setText("Nam");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Số điện thoại ");

        txt_sdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_sdt.setForeground(new java.awt.Color(0, 0, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Email");

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(0, 0, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Ngày sinh");

        txt_nsinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_nsinh.setForeground(new java.awt.Color(0, 0, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Ngày tạo");

        txt_ntao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_ntao.setForeground(new java.awt.Color(0, 0, 204));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("Ghi chú");

        txt_gchu.setColumns(20);
        txt_gchu.setForeground(new java.awt.Color(0, 0, 204));
        txt_gchu.setRows(5);
        jScrollPane2.setViewportView(txt_gchu);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Mã NV");

        txt_ma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_ma.setForeground(new java.awt.Color(0, 0, 204));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("Mật khẩu");

        txt_mk1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_mk1.setForeground(new java.awt.Color(0, 0, 204));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("Xác nhật mật khẩu");

        txt_mk2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_mk2.setForeground(new java.awt.Color(0, 0, 204));
        txt_mk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mk2ActionPerformed(evt);
            }
        });

        txt_anh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 5));
        txt_anh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_anhMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Vai trò");

        buttonGroup2.add(rdoQL);
        rdoQL.setForeground(new java.awt.Color(0, 0, 204));
        rdoQL.setText("Quản lí");
        rdoQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoQLActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdoNV);
        rdoNV.setForeground(new java.awt.Color(0, 0, 204));
        rdoNV.setText("Nhân Viên");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(605, 903, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rdoQL)
                                .addGap(18, 18, 18)
                                .addComponent(rdoNV)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(txt_ten, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rdoNam)
                                        .addGap(30, 30, 30)
                                        .addComponent(rdoNu))
                                    .addComponent(txt_anh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txt_dChi, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(txt_mk1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(txt_mk2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ntao, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txt_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoNu)
                            .addComponent(rdoNam)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_mk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_mk2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_dChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ntao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(15, 15, 15)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoQL)
                    .addComponent(rdoNV))
                .addGap(12, 12, 12))
        );

        tblactive.setForeground(new java.awt.Color(0, 0, 204));
        tblactive.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Họ và tên", "SDT", "Email", "Ngày sinh", "Giới tính", "Địa chỉ", "Vai trò", "Ngày bắt đầu", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblactive.setGridColor(new java.awt.Color(255, 255, 255));
        tblactive.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tblactive.setRowHeight(30);
        tblactive.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblactive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblactiveMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblactive);
        if (tblactive.getColumnModel().getColumnCount() > 0) {
            tblactive.getColumnModel().getColumn(0).setMinWidth(100);
            tblactive.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblactive.getColumnModel().getColumn(1).setMinWidth(70);
            tblactive.getColumnModel().getColumn(1).setPreferredWidth(10);
            tblactive.getColumnModel().getColumn(2).setMinWidth(70);
            tblactive.getColumnModel().getColumn(2).setPreferredWidth(10);
            tblactive.getColumnModel().getColumn(3).setResizable(false);
            tblactive.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblactive.getColumnModel().getColumn(4).setMinWidth(60);
            tblactive.getColumnModel().getColumn(4).setPreferredWidth(10);
            tblactive.getColumnModel().getColumn(4).setMaxWidth(60);
            tblactive.getColumnModel().getColumn(5).setResizable(false);
            tblactive.getColumnModel().getColumn(5).setPreferredWidth(10);
            tblactive.getColumnModel().getColumn(6).setMaxWidth(50);
            tblactive.getColumnModel().getColumn(7).setPreferredWidth(10);
            tblactive.getColumnModel().getColumn(8).setMinWidth(60);
            tblactive.getColumnModel().getColumn(8).setMaxWidth(70);
        }

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete_1.png"))); // NOI18N
        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        jButton4.setText("Sửa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        jButton5.setText("Mới");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 204));
        jButton6.setText("<<");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        vitri.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vitri.setForeground(new java.awt.Color(0, 0, 204));
        vitri.setText("1");
        vitri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitriActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 204));
        jButton9.setText(">>");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("Search");

        jButton10.setText("Tên");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton1.setText("SDT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txt_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(vitri, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(420, 420, 420)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(jButton3)
                            .addGap(28, 28, 28)
                            .addComponent(jButton4)
                            .addGap(27, 27, 27)
                            .addComponent(jButton5))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jButton10)
                    .addComponent(txt_tk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vitri)
                            .addComponent(jButton6)
                            .addComponent(jButton9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("NHÂN VIÊN", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (page > 1) {
            page--;
        }
        vitri.setText(page + "");
        loadDataToTable();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tblactiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblactiveMouseClicked
        // TODO add your handling code here:
        index = tblactive.getSelectedRow();
        System.out.println(list.get(index).getAnhNhanVien());
        showDetail();
    }//GEN-LAST:event_tblactiveMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        newform();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void vitriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vitriActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        page++;
        vitri.setText(page + "");
        loadDataToTable();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        NhanVien nv = list.get(index);
        if (service.checkKN(nv.getMaNhanVien()).getMaNhanVien() != null) {
            JOptionPane.showMessageDialog(null, "Nhân viên đã có trong hóa đơn!Không thể xóa!");
            nv.setTrangThai(false);
            service.update(nv);
            JOptionPane.showMessageDialog(null, "Đã chuyển trạng thái");
            loadDataToTable();
            return;
        }
        delete(nv);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (!isValidate()) {
            JOptionPane.showMessageDialog(null, "Không được để trống");
            return;
        }
        NhanVien nv = readForm();
        nv.setNgayTao(XDate.toString(XDate.now(), "dd-MM-yyyy"));
        nv.setAnhNhanVien(path1);
        Integer x = service.insert(nv);
        if (x != null) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            page = 1;
            loadDataToTable();
            newform();
        } else
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (!isValidate()) {
            JOptionPane.showMessageDialog(null, "Không được để trống");
            return;
        }
        NhanVien nv = readForm();
        nv.setTrangThai((boolean) tblactive.getValueAt(index, 8));
        nv.setAnhNhanVien(list.get(index).getAnhNhanVien());
        System.out.println(list.get(index).getAnhNhanVien());
        capnhat(nv);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void rdoQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoQLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoQLActionPerformed

    private void txt_mk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mk2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        ten = txt_tk.getText();
        sdt = "";
        loadDataToTable();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void txt_anhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_anhMouseClicked
        // TODO add your handling code here:
        path1 = fileChoose.chooseFile();
        java.awt.Image orImage = new ImageIcon(path + path1).getImage();
        java.awt.Image resize = orImage.getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
        txt_anh.setIcon(new ImageIcon(resize));
    }//GEN-LAST:event_txt_anhMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ten = "";
        sdt = txt_tk.getText();
        loadDataToTable();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JRadioButton rdoNV;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JRadioButton rdoQL;
    private javax.swing.JTable tblactive;
    private javax.swing.JLabel txt_anh;
    private javax.swing.JTextField txt_dChi;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextArea txt_gchu;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_mk1;
    private javax.swing.JTextField txt_mk2;
    private javax.swing.JTextField txt_nsinh;
    private javax.swing.JTextField txt_ntao;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_tk;
    private javax.swing.JButton vitri;
    // End of variables declaration//GEN-END:variables

    private void loadDataToTable() {
        model.setRowCount(0);
        list = service.paging(page, 5, sdt, ten);
        for (NhanVien x : list) {
            model.addRow(new Object[]{x.getTenNhanVien(), x.getSoDienThoai(), x.getEmail(), x.getNgaySinh(),
                x.isGioiTinh() ? "Nam" : "Nữ", x.getDiaChi(), x.isVaiTro(), x.getNgayTao(),
                x.getTrangThai(),x.getAnhNhanVien()});
        }
    }

    public void showDetail() {
        NhanVien x = list.get(index);
        txt_ma.setText(x.getMaNhanVien());
        txt_ten.setText(x.getTenNhanVien());
        txt_sdt.setText(x.getSoDienThoai());
        txt_nsinh.setText(x.getNgaySinh());
        txt_dChi.setText(x.getDiaChi());
        txt_email.setText(x.getEmail());
        txt_gchu.setText("");
        txt_ntao.setText(x.getNgayTao());
        txt_mk1.setText(x.getMatKhau());
        txt_mk2.setText(x.getMatKhau());
        if (x.isGioiTinh()) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
        if (x.isVaiTro()) {
            rdoQL.setSelected(true);
        } else {
            rdoNV.setSelected(true);
        }
        java.awt.Image orImage = new ImageIcon(path + x.getAnhNhanVien()).getImage();
        java.awt.Image resize = orImage.getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
        txt_anh.setIcon(new ImageIcon(resize));
    }

    public NhanVien readForm() {
        String pattern = "yyyy-MM-dd";
        NhanVien x = list.get(index);
        x.setMaNhanVien(txt_ma.getText());
        x.setMatKhau(txt_mk1.getText());
        x.setTenNhanVien(txt_ten.getText());
        x.setSoDienThoai(txt_sdt.getText());
        x.setDiaChi(txt_dChi.getText());
        x.setNgaySinh(txt_nsinh.getText());
        x.setGioiTinh(rdoNam.isSelected() ? true : false);
        x.setEmail(txt_email.getText());
        x.setNgayTao(txt_ntao.getText());
        x.setVaiTro(rdoQL.isSelected() ? true : false);
        x.setTrangThai(true);
        return x;
    }

    private void newform() {
        ten = "";
        sdt = "";
        path1 = "";
        txt_ma.setText("");
        txt_ten.setText("");
        txt_mk1.setText("");
        txt_mk2.setText("");
        txt_sdt.setText("");
        txt_nsinh.setText("");
        txt_dChi.setText("");
        txt_email.setText("");
        txt_gchu.setText("");
        txt_ntao.setText(XDate.toString(XDate.now(), "dd-MM-yyyy"));
        loadDataToTable();
    }

    private boolean isValidate() {
        if (txt_ma.getText().isEmpty() || txt_ten.getText().isEmpty() || txt_sdt.getText().isEmpty() || txt_nsinh.getText().isEmpty()
                || txt_email.getText().isEmpty() || txt_dChi.getText().isEmpty() || txt_mk1.getText().isEmpty()
                || txt_mk2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Không được để trống");
            return false;
        }
        if (!txt_mk1.getText().equals(txt_mk2.getText())) {
            JOptionPane.showMessageDialog(null, "Mật khẩu không trùng khớp");
            return false;
        }
        return true;
    }

    public void capnhat(NhanVien nv) {
        Integer x = service.update(nv);
        if (x != null) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            page = 1;
            loadDataToTable();
            newform();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
    }

    public void delete(NhanVien nv) {
        Integer chon = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn xóa chứ");
        if (chon != 0) {
            return;
        }
        Integer rs = service.delete(nv.getMaNhanVien());
        if (rs != null) {
            JOptionPane.showMessageDialog(null, "Xóa thành công");
            loadDataToTable();
        } else {
            JOptionPane.showMessageDialog(null, "Xóa thất bại");
        }
    }
}
