/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.BoNhoTrong;
import models.CPU;
import models.Camera;
import models.Hang;
import models.HeDieuHanh;
import models.Imei;
import models.LoaiHang;
import models.ManHinh;
import models.MauSac;
import models.NhanVien;
import models.Ram;
import models.SanPham;
import models.SanPhamChiTiet;
import models.XuatXu;
import org.apache.poi.sl.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Cell;
import static org.apache.poi.ss.usermodel.CellType.NUMERIC;
import static org.apache.poi.ss.usermodel.CellType.STRING;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import services.BoNhoTrongService;
import services.CPUService;
import services.CameraService;
import services.HangService;
import services.HeDieuHanhService;
import services.ImeiService;
import services.KhachHangService;
import services.LoaiHangService;
import services.ManHinhService;
import services.MauSacService;
import services.NhanVienService;
import services.RamService;
import services.SanPhamService;
import services.XuatXuService;
import utils.CustomRenderer;

import utils.XDate;
import utils.fileChoose;

public class SanPhamView extends javax.swing.JPanel {

    ArrayList<SanPhamChiTiet> list = new ArrayList<>();
    ArrayList<Imei> imeis = new ArrayList<>();
    ArrayList<String> data = new ArrayList<>();
    int page = 1, index = 1;

    DefaultTableModel model = new DefaultTableModel();
    DefaultComboBoxModel<ManHinh> mhmodel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<MauSac> msmodel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<Hang> hmodel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<HeDieuHanh> hdhmodel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<BoNhoTrong> bntmodel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<Camera> cameramodel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<Ram> rammodel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<CPU> cpumodel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<XuatXu> xuatxumodel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<LoaiHang> loaihangmodel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> spmodel = new DefaultComboBoxModel<>();

    SanPhamService service = new SanPhamService();
    ManHinhService mhs = new ManHinhService();
    MauSacService mss = new MauSacService();
    HangService hs = new HangService();
    HeDieuHanhService hdhs = new HeDieuHanhService();
    BoNhoTrongService bnts = new BoNhoTrongService();
    CameraService cmrs = new CameraService();
    RamService rams = new RamService();
    CPUService cpus = new CPUService();
    XuatXuService xxs = new XuatXuService();
    LoaiHangService lhs = new LoaiHangService();
    ImeiService imeiservice = new ImeiService();

    String path = "C:\\Users\\dovan\\OneDrive\\Desktop\\images\\";
    String path1 = "";
    String ten = "", trangThai = "";

    public SanPhamView() {
        initComponents();
        model = (DefaultTableModel) tblactive.getModel();

        mhmodel = (DefaultComboBoxModel<ManHinh>) cbo_mh.getModel();
        msmodel = (DefaultComboBoxModel<MauSac>) cbo_mausac.getModel();
        hmodel = (DefaultComboBoxModel<Hang>) cbo_hang.getModel();
        bntmodel = (DefaultComboBoxModel<BoNhoTrong>) cbo_bnt.getModel();
        cameramodel = (DefaultComboBoxModel<Camera>) cbo_camera.getModel();
        rammodel = (DefaultComboBoxModel<Ram>) cbo_ram.getModel();
        cpumodel = (DefaultComboBoxModel<CPU>) cbo_cpu.getModel();
        xuatxumodel = (DefaultComboBoxModel<XuatXu>) cbo_xuatxu.getModel();
        loaihangmodel = (DefaultComboBoxModel<LoaiHang>) cbo_loaiHang.getModel();
        hdhmodel = (DefaultComboBoxModel<HeDieuHanh>) cbo_hdh.getModel();

        loadDataToCombo();
        loadDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbo_bnt = new javax.swing.JComboBox<>();
        cbo_hang = new javax.swing.JComboBox<>();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbo_camera = new javax.swing.JComboBox<>();
        jButton15 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbo_mausac = new javax.swing.JComboBox<>();
        jButton16 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbo_ram = new javax.swing.JComboBox<>();
        jButton17 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbo_hdh = new javax.swing.JComboBox<>();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        cbo_cpu = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbo_xuatxu = new javax.swing.JComboBox<>();
        jButton20 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbo_loaiHang = new javax.swing.JComboBox<>();
        jButton21 = new javax.swing.JButton();
        cbo_mh = new javax.swing.JComboBox<>();
        jButton22 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cbo_imei = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        lbl_sl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblactive = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        vitri = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        txt_tim = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txt_anh = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_giaban = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_gianhap = new javax.swing.JTextField();
        txt_ten = new javax.swing.JTextField();
        txt_ma = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Ngày tạo");

        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Bộ nhớ trong");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 96, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("Hãng");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Màn hình");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 95, -1));

        cbo_bnt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(cbo_bnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, -1));

        cbo_hang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbo_hang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_hangActionPerformed(evt);
            }
        });
        jPanel3.add(cbo_hang, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 140, -1));

        jButton12.setBackground(new java.awt.Color(0, 0, 204));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("+");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 150, -1));

        jButton13.setBackground(new java.awt.Color(0, 0, 204));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("+");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 130, -1));

        jButton14.setBackground(new java.awt.Color(0, 0, 204));
        jButton14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("+");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 140, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Camera");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 96, -1));

        cbo_camera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(cbo_camera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, -1));

        jButton15.setBackground(new java.awt.Color(0, 0, 204));
        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("+");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Màu sắc");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 96, -1));

        cbo_mausac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(cbo_mausac, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 140, -1));

        jButton16.setBackground(new java.awt.Color(0, 0, 204));
        jButton16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("+");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 140, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Dung lượng Ram");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 128, -1));

        cbo_ram.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(cbo_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 130, -1));

        jButton17.setBackground(new java.awt.Color(0, 0, 204));
        jButton17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("+");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 130, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Hệ Điều Hành");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 96, -1));

        cbo_hdh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbo_hdh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_hdhActionPerformed(evt);
            }
        });
        jPanel3.add(cbo_hdh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, -1));

        jButton18.setBackground(new java.awt.Color(0, 0, 204));
        jButton18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("+");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, -1));

        jButton19.setBackground(new java.awt.Color(0, 0, 204));
        jButton19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("+");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 140, -1));

        cbo_cpu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(cbo_cpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 140, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("CPU");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 96, -1));

        cbo_xuatxu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(cbo_xuatxu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 130, -1));

        jButton20.setBackground(new java.awt.Color(0, 0, 204));
        jButton20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("+");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 130, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Xuất Xứ");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 96, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("Loại Hàng");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 96, -1));

        cbo_loaiHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(cbo_loaiHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 150, -1));

        jButton21.setBackground(new java.awt.Color(0, 0, 204));
        jButton21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("+");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, -1));

        cbo_mh.setEditable(true);
        cbo_mh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbo_mh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_mhActionPerformed(evt);
            }
        });
        jPanel3.add(cbo_mh, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 130, -1));

        jButton22.setBackground(new java.awt.Color(0, 0, 204));
        jButton22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("import");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 130, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 204));
        jLabel18.setText("Danh sách imei");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        cbo_imei.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(cbo_imei, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 140, -1));

        jButton11.setBackground(new java.awt.Color(0, 0, 204));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("+");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 140, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 204));
        jLabel20.setText("Ngày tạo");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 70, -1));

        txt_date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_date.setForeground(new java.awt.Color(0, 0, 204));
        txt_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dateActionPerformed(evt);
            }
        });
        jPanel3.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 130, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 204));
        jLabel21.setText("Danh sách imei");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 140, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 204));
        jLabel22.setText("Số lượng");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, -1));

        lbl_sl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_sl.setText("()");
        jPanel3.add(lbl_sl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        tblactive.setForeground(new java.awt.Color(0, 0, 204));
        tblactive.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên SP", "Loại", "Ram", "Rom ", "Màn hình", "Màu sắc", "SL", "Giá", "Trạng Thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblactive.setGridColor(new java.awt.Color(255, 255, 255));
        tblactive.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tblactive.setRowHeight(30);
        tblactive.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblactive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblactiveMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblactive);
        if (tblactive.getColumnModel().getColumnCount() > 0) {
            tblactive.getColumnModel().getColumn(0).setMaxWidth(50);
            tblactive.getColumnModel().getColumn(1).setMinWidth(120);
            tblactive.getColumnModel().getColumn(1).setPreferredWidth(20);
            tblactive.getColumnModel().getColumn(2).setMinWidth(20);
            tblactive.getColumnModel().getColumn(2).setPreferredWidth(10);
            tblactive.getColumnModel().getColumn(3).setMinWidth(70);
            tblactive.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblactive.getColumnModel().getColumn(4).setMinWidth(70);
            tblactive.getColumnModel().getColumn(4).setPreferredWidth(10);
            tblactive.getColumnModel().getColumn(5).setResizable(false);
            tblactive.getColumnModel().getColumn(5).setPreferredWidth(70);
            tblactive.getColumnModel().getColumn(6).setMinWidth(70);
            tblactive.getColumnModel().getColumn(7).setResizable(false);
            tblactive.getColumnModel().getColumn(7).setPreferredWidth(10);
            tblactive.getColumnModel().getColumn(8).setMinWidth(100);
            tblactive.getColumnModel().getColumn(8).setPreferredWidth(10);
            tblactive.getColumnModel().getColumn(9).setMaxWidth(70);
        }

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        jButton4.setText("Sửa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        jButton5.setText("Mới");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 204));
        jButton6.setText("<<");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        vitri.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vitri.setForeground(new java.awt.Color(0, 0, 204));
        vitri.setText("1");
        vitri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitriActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 204));
        jButton9.setText(">>");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("Search");

        jButton10.setText("Tìm");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        txt_tim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_tim.setForeground(new java.awt.Color(0, 0, 204));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        txt_anh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 5));
        txt_anh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_anhMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("Tên SP");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 204));
        jLabel17.setText("Giá bán");

        txt_giaban.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_giaban.setForeground(new java.awt.Color(0, 0, 204));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 204));
        jLabel19.setText("Giá nhập");

        txt_gianhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_gianhap.setForeground(new java.awt.Color(0, 0, 204));

        txt_ten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_ma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 204));
        jLabel16.setText("Mã SP");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_anh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_gianhap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_giaban, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txt_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(0, 0, 0)
                .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(0, 0, 0)
                .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(0, 0, 0)
                .addComponent(txt_giaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(0, 0, 0)
                .addComponent(txt_gianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setText("Excel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vitri, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(406, 406, 406)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(12, 12, 12)
                            .addComponent(txt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton10))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1037, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jButton10)
                    .addComponent(txt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vitri)
                    .addComponent(jButton6)
                    .addComponent(jButton9)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("SẢN PHẨM", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (page > 1) {
            page--;
        }
        vitri.setText(page + "");
        loadDataToTable();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tblactiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblactiveMouseClicked
        // TODO add your handling code here:
        index = tblactive.getSelectedRow();
        showDetail();
        setform();
    }//GEN-LAST:event_tblactiveMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        newform();
        setform();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void vitriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vitriActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        page++;
        vitri.setText(page + "");
        loadDataToTable();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SanPham sp = readFormSP();
        SanPhamChiTiet spct = readFormSPCT();
        spct.setTrangThai(true);
        Integer rs = service.insertSPCT(sp, spct);
        if (rs != null) {
            JOptionPane.showMessageDialog(null, "Thêm thành công!");
            loadDataToTable();
            themimei(service.searchNewSPCT());
        } else
            JOptionPane.showMessageDialog(null, "Thêm thất bại!");
    }//GEN-LAST:event_jButton2ActionPerformed

    public Integer themimei(int maSPCT) {
        for (Imei x : imeis) {
            x.setMaSanPhamChiTiet(maSPCT);
            x.setTrangThai(true);
            imeiservice.insert(x);
        }
        return null;
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        SanPham sp = readFormSP();
        SanPhamChiTiet spct = readFormSPCT();
        if(sp.getAnh()==null){
            sp.setAnh(service.searchByid(sp.getMaSP()).getAnh());
        }
        spct.setTrangThai((boolean) tblactive.getValueAt(index, 9));
        spct.setMaSPCT(list.get(index).getMaSPCT());
        Integer x = service.updateSPCT(spct, sp);
        if (x != null) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            System.out.println(spct.isTrangThai());
            page = 1;
            loadDataToTable();
            newform();
        } else
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        ten = txt_tim.getText();
        loadDataToTable();

    }//GEN-LAST:event_jButton10ActionPerformed

    private void txt_anhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_anhMouseClicked
        // TODO add your handling code here:
        path1 = fileChoose.chooseFile();
        java.awt.Image orImage = new ImageIcon(path + path1).getImage();
        java.awt.Image resize = orImage.getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
        txt_anh.setIcon(new ImageIcon(resize));
    }//GEN-LAST:event_txt_anhMouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        imeis.removeAll(imeis);
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            imeis = importExcelData(selectedFile);
            // Do something with the imported data (data List)
            loadImei();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void cbo_hdhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_hdhActionPerformed
        // TODO add your handling code here:
        loadDataToDanhMuc();
    }//GEN-LAST:event_cbo_hdhActionPerformed

    private void cbo_mhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_mhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_mhActionPerformed

    private void cbo_hangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_hangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_hangActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void txt_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<BoNhoTrong> cbo_bnt;
    private javax.swing.JComboBox<Camera> cbo_camera;
    private javax.swing.JComboBox<CPU> cbo_cpu;
    private javax.swing.JComboBox<Hang> cbo_hang;
    private javax.swing.JComboBox<HeDieuHanh> cbo_hdh;
    private javax.swing.JComboBox<String> cbo_imei;
    private javax.swing.JComboBox<LoaiHang> cbo_loaiHang;
    private javax.swing.JComboBox<MauSac> cbo_mausac;
    private javax.swing.JComboBox<ManHinh> cbo_mh;
    private javax.swing.JComboBox<Ram> cbo_ram;
    private javax.swing.JComboBox<XuatXu> cbo_xuatxu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lbl_sl;
    private javax.swing.JTable tblactive;
    private javax.swing.JLabel txt_anh;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_giaban;
    private javax.swing.JTextField txt_gianhap;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_tim;
    private javax.swing.JButton vitri;
    // End of variables declaration//GEN-END:variables

    private void loadDataToTable() {
        model.setRowCount(0);
        list = service.pagingByTen(page, 5, ten, trangThai);
        int vi = 1;
        if (page != 1) {
            vi = page * 5 + 1;
        }
        for (SanPhamChiTiet spct : list) {
            SanPham sp = service.searchByid(spct.getMaSP());
            model.addRow(new Object[]{vi, sp.getTen(), lhs.searchById(spct.getMaLoaiHang()), rams.searchByID(spct.getMaRam()).toString(),
                bnts.searchByID(spct.getMaBoNhoTrong()).toString(), mhs.searchById(spct.getMaManHinh()).toString(),
                mss.searchByID(spct.getMaMauSac()), "", spct.getGiaBan(), spct.isTrangThai()});
            vi++;
        }
    }

    public void showDetail() {
        SanPhamChiTiet spct = list.get(index);
        SanPham sp = service.searchByid(spct.getMaSP());
        java.awt.Image orImage = new ImageIcon(path + sp.getAnh()).getImage();
        java.awt.Image resize = orImage.getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
        txt_anh.setIcon(new ImageIcon(resize));
        txt_ten.setText(sp.getTen());
        txt_ma.setText(sp.getMaSP());
        txt_giaban.setText(String.valueOf(spct.getGiaBan()));
        txt_gianhap.setText(String.valueOf(spct.getGiaNhap()));
        txt_date.setText(spct.getNgayTao());
        hdhmodel.setSelectedItem(hdhs.searchById(sp.getMaHDH()));
        hmodel.setSelectedItem(hs.searchById(sp.getMaHang()));
        mhmodel.setSelectedItem(mhs.searchById(spct.getMaManHinh()));
        msmodel.setSelectedItem(mss.searchByID(spct.getMaMauSac()));
        bntmodel.setSelectedItem(bnts.searchByID(spct.getMaBoNhoTrong()));
        rammodel.setSelectedItem(rams.searchByID(spct.getMaRam()));
        cameramodel.setSelectedItem(cmrs.searchByID(spct.getMaCamera()));
        xuatxumodel.setSelectedItem(xxs.searchByID(spct.getMaXuatXu()));
        loaihangmodel.setSelectedItem(lhs.searchById(spct.getMaLoaiHang()));
        cpumodel.setSelectedItem(cpus.searchByID(spct.getMaCPU()));
        imeis = service.soLuongTonSP(spct.getMaSPCT(), "1");
        loadImei();
    }

    public void loadImei() {
        cbo_imei.removeAllItems();
        for (Imei g : imeis) {
            cbo_imei.addItem(g.getSoImei());
        }
        lbl_sl.setText("(" + imeis.size() + ")");
    }

    public SanPhamChiTiet readFormSPCT() {
        String pattern = "yyyy-MM-dd";
        SanPhamChiTiet spct = new SanPhamChiTiet();
        ManHinh mh = (ManHinh) cbo_mh.getSelectedItem();
        MauSac ms = (MauSac) cbo_mausac.getSelectedItem();
        BoNhoTrong bnt = (BoNhoTrong) cbo_bnt.getSelectedItem();
        Ram ram = (Ram) cbo_ram.getSelectedItem();
        CPU cpu = (CPU) cbo_cpu.getSelectedItem();
        XuatXu xx = (XuatXu) cbo_xuatxu.getSelectedItem();
        Camera camera = (Camera) cbo_camera.getSelectedItem();
        LoaiHang loaiHang = (LoaiHang) cbo_loaiHang.getSelectedItem();
        spct.setMaSP(txt_ma.getText());
        spct.setMaMauSac(ms.getMa());
        spct.setMaManHinh(mh.getMaManHinh());
        spct.setMaBoNhoTrong(bnt.getMa());
        spct.setMaCamera(camera.getMa());
        spct.setMaRam(ram.getMa());
        spct.setMaCPU(cpu.getMa());
        spct.setMaXuatXu(xx.getMa());
        spct.setMaLoaiHang(loaiHang.getMa());
        spct.setGiaNhap(Double.valueOf(txt_gianhap.getText()));
        spct.setGiaBan(Double.valueOf(txt_giaban.getText()));
        spct.setNgayTao(txt_date.getText());
        return spct;
    }

    public SanPham readFormSP() {
        SanPham x = new SanPham();
        Hang hang = (Hang) cbo_hang.getSelectedItem();
        HeDieuHanh hdh = (HeDieuHanh) cbo_hdh.getSelectedItem();
        x.setMaSP(txt_ma.getText());
        x.setMota("x");
        x.setTen(txt_ten.getText());
        if (path1 != "") {
            x.setAnh(path1);
        }
        x.setMaHDH(hdh.getMa());
        x.setMaHang(hang.getMa());
        return x;
    }

    private void newform() {
        ten = "";
        path1 = "";
        imeis.removeAll(imeis);
        txt_ma.setText("");
        txt_ten.setText("");
        txt_anh.setIcon(new ImageIcon());
        txt_date.setText(XDate.toString(XDate.now(), "dd-MM-yyyy"));
        txt_giaban.setText("");
        txt_gianhap.setText("");
        imeis.removeAll(imeis);
        bntmodel.setSelectedItem("");
        cameramodel.setSelectedItem("");
        cpumodel.setSelectedItem("");
        hmodel.setSelectedItem("");
        cbo_imei.setSelectedItem("");
        loaihangmodel.setSelectedItem("");
        msmodel.setSelectedItem("");
        mhmodel.setSelectedItem("");
        rammodel.setSelectedItem("");
        xuatxumodel.setSelectedItem("");
        index = -1;
        loadImei();
        loadDataToTable();
    }

    private void loadDataToCombo() {
        mhmodel.removeAllElements();
        msmodel.removeAllElements();
        hmodel.removeAllElements();
        bntmodel.removeAllElements();
        cameramodel.removeAllElements();
        rammodel.removeAllElements();
        cameramodel.removeAllElements();
        cpumodel.removeAllElements();
        xuatxumodel.removeAllElements();
        loaihangmodel.removeAllElements();
        hdhmodel.removeAllElements();
        ArrayList<ManHinh> li = mhs.paging();
        for (ManHinh x : li) {
            if (x.getTrangThai()) {
                mhmodel.addElement(x);
            }
        }
        ArrayList<MauSac> li1 = mss.getAll();
        for (MauSac x : li1) {
            if (x.isTrangThai()) {
                msmodel.addElement(x);
            }
        }
        ArrayList<BoNhoTrong> li2 = bnts.getAll();
        for (BoNhoTrong x : li2) {
            if (x.isTrangThai()) {
                bntmodel.addElement(x);
            }
        }
        ArrayList<HeDieuHanh> li9 = hdhs.getAll();
        for (HeDieuHanh x : li9) {
            if (x.isTrangThai()) {
                hdhmodel.addElement(x);
            }
        }
        hmodel.removeAllElements();
        HeDieuHanh hdh = (HeDieuHanh) hdhmodel.getSelectedItem();
        if (hdh != null) {
            ArrayList<Hang> li3 = hs.getAll(String.valueOf(hdh.getMa()));
            for (Hang x : li3) {
                if (x.isTrangThai()) {
                    hmodel.addElement(x);
                }
            }
        }
        ArrayList<Camera> li4 = cmrs.getAll();
        for (Camera x : li4) {
            if (x.isTrangThai()) {
                cameramodel.addElement(x);
            }
        }
        ArrayList<Ram> li5 = rams.getAll();
        for (Ram x : li5) {
            if (x.isTrangThai()) {
                rammodel.addElement(x);
            }
        }
        ArrayList<CPU> li6 = cpus.getAll();
        for (CPU x : li6) {
            if (x.isTrangThai()) {
                cpumodel.addElement(x);
            }
        }
        ArrayList<XuatXu> li7 = xxs.getAll();
        for (XuatXu x : li7) {
            if (x.isTrangThai()) {
                xuatxumodel.addElement(x);
            }
        }
        ArrayList<LoaiHang> li8 = lhs.getAll();
        for (LoaiHang x : li8) {
            if (x.isTrangThai()) {
                loaihangmodel.addElement(x);
            }
        }
    }

    private void loadDataToDanhMuc() {
        hmodel.removeAllElements();
        HeDieuHanh hdh = (HeDieuHanh) hdhmodel.getSelectedItem();
        ArrayList<Hang> li3 = hs.getAll(String.valueOf(hdh.getMa()));
        for (Hang x : li3) {
            hmodel.addElement(x);
        }
    }

    private static ArrayList<Imei> importExcelData(File file) {
        ArrayList<Imei> data = new ArrayList<>();

        try (FileInputStream fis = new FileInputStream(file); Workbook workbook = new XSSFWorkbook(fis)) {
            org.apache.poi.ss.usermodel.Sheet sheet = workbook.getSheetAt(0); // Assuming you want to read the first sheet
            for (Row row : sheet) {
                Imei x = new Imei();
                String so = String.valueOf(row.getCell(0).getNumericCellValue());
                double doubleValue = Double.parseDouble(so);
                long intValue = Math.round(doubleValue); // Làm tròn giá trị số thực thành số nguyên
                String formattedValue = String.valueOf(intValue);
                x.setSoImei(formattedValue);
//                x.setMaSanPhamChiTiet((int) row.getCell(1).getNumericCellValue());
                data.add(x);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return data;
    }

    public void qrcode(Imei imei) {
        int size = 200; // Kích thước của mã QR code
        String text = imei.getSoImei();
        try {
            QRCodeWriter qrCodeWriter = new QRCodeWriter();
            BitMatrix bitMatrix = qrCodeWriter.encode(text, BarcodeFormat.QR_CODE, size, size);
            BufferedImage image = MatrixToImageWriter.toBufferedImage(bitMatrix);

            // Đường dẫn mặc định là ổ C và tên tệp là "QRCode.png"
            String defaultDirectory = "C:\\Users\\dovan\\OneDrive\\Desktop\\images\\QRCode";
            String fileName = String.valueOf(imei.getMaSanPhamChiTiet()) + ".png";
            File outputFile = new File(defaultDirectory, fileName);

            ImageIO.write(image, "PNG", outputFile);

            JOptionPane.showMessageDialog(null, "QR Code saved to: " + outputFile.getAbsolutePath());
        } catch (WriterException | IOException ex) {
            ex.printStackTrace();
        }
    }

    public void setform() {
        if (index == -1) {
            txt_ma.setEnabled(true);
            txt_ten.setEnabled(true);
            cbo_hang.setEnabled(true);
            cbo_hdh.setEnabled(true);

        } else {
            txt_ma.setEnabled(false);
            txt_ten.setEnabled(false);
            cbo_hang.setEnabled(false);
            cbo_hdh.setEnabled(false);
        }
    }
}
