/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Hang;
import models.HeDieuHanh;
import models.SanPham;
import services.HangService;
import services.HeDieuHanhService;
import services.SanPhamService;
import utils.fileChoose;

/**
 *
 * @author dovan
 */
public class ThemSanPham extends javax.swing.JFrame {

    /**
     * Creates new form ThemSanPham
     */
    
    String path = "C:\\Users\\dovan\\OneDrive\\Desktop\\images\\";
    String path1 = "";
    String ten = "";
    int index=-1;
    SanPhamService service = new SanPhamService();
    HangService hs = new HangService();
    HeDieuHanhService hdhs = new HeDieuHanhService();
    ArrayList<SanPham> list1 = new ArrayList<>();
    ArrayList<SanPham> list2 = new ArrayList<>();
    
    DefaultTableModel model1 = new DefaultTableModel();
    DefaultComboBoxModel<Hang> hmodel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<HeDieuHanh> hdhmodel = new DefaultComboBoxModel<>();
    public ThemSanPham() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        model1 = (DefaultTableModel)tbl1.getModel();
        loadDataToTablel();
        hdhmodel = (DefaultComboBoxModel<HeDieuHanh>)cbo_hdh.getModel();
        hmodel = (DefaultComboBoxModel<Hang>)cbo_hang.getModel();
        ArrayList<HeDieuHanh> li9 = hdhs.getAll();
        for (HeDieuHanh x : li9) {
            hdhmodel.addElement(x);
        }
        loadDataToDanhMuc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_anh = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbo_sp = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        txt_anh1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cbo_hdh = new javax.swing.JComboBox<>();
        cbo_hang = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();

        txt_anh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 5));
        txt_anh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_anhMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("Tên SP");

        cbo_sp.setEditable(true);
        cbo_sp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbo_sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_spActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã", "Tên Dòng", "Trạng Thái"
            }
        ));
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl1);
        if (tbl1.getColumnModel().getColumnCount() > 0) {
            tbl1.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        txt_anh1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 5));
        txt_anh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_anh1MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 204));
        jLabel16.setText("Tên ");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 204));
        jLabel17.setText("Mã");

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");

        jButton4.setText("Mới");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 204));
        jLabel18.setText("Hệ Điều Hành");

        cbo_hdh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_hdhActionPerformed(evt);
            }
        });

        cbo_hang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_hangActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 204));
        jLabel19.setText("Hãng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addGap(12, 12, 12)
                        .addComponent(jButton2))
                    .addComponent(jLabel18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbo_hdh, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_anh1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_ma, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_ten, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbo_hang, javax.swing.GroupLayout.Alignment.LEADING, 0, 235, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txt_anh1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbo_hdh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbo_hang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton2))
                .addGap(17, 17, 17))
        );

        jTabbedPane1.addTab("SẢN PHẨM", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_anhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_anhMouseClicked
        // TODO add your handling code here:
        path1 = fileChoose.chooseFile();
        java.awt.Image orImage = new ImageIcon(path + path1).getImage();
        java.awt.Image resize = orImage.getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
        txt_anh.setIcon(new ImageIcon(resize));
    }//GEN-LAST:event_txt_anhMouseClicked

    private void cbo_spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_spActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_spActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        txt_ma.setText("");
        txt_ten.setText("");
        txt_anh1.setIcon(new ImageIcon());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Integer chon = service.insert(readForm());
        if(chon!=null){
            JOptionPane.showMessageDialog(null, "Thêm thành công");
            loadDataToTablel();
        }else JOptionPane.showMessageDialog(null, "Thêm thất bại");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_anh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_anh1MouseClicked
        // TODO add your handling code here:
        path1 = fileChoose.chooseFile();
        java.awt.Image orImage = new ImageIcon(path + path1).getImage();
        java.awt.Image resize = orImage.getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
        txt_anh1.setIcon(new ImageIcon(resize));
    }//GEN-LAST:event_txt_anh1MouseClicked

    private void tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseClicked
        // TODO add your handling code here:
        index = tbl1.getSelectedRow();
        showdetail();
    }//GEN-LAST:event_tbl1MouseClicked

    private void cbo_hdhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_hdhActionPerformed
        // TODO add your handling code here:
        loadDataToDanhMuc();
    }//GEN-LAST:event_cbo_hdhActionPerformed

    private void cbo_hangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_hangActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbo_hangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Hang> cbo_hang;
    private javax.swing.JComboBox<HeDieuHanh> cbo_hdh;
    private javax.swing.JComboBox<String> cbo_sp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl1;
    private javax.swing.JLabel txt_anh;
    private javax.swing.JLabel txt_anh1;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_ten;
    // End of variables declaration//GEN-END:variables

    private void loadDataToTablel() {
        model1.setRowCount(0);
        list1 = service.getall();
        for(SanPham x : list1){
            model1.addRow(new Object[]{x.getMa(),x.getTen()});
        }
    }
    
    public void showdetail(){
        SanPham x = list1.get(index);
        txt_ten.setText(x.getTen());
        txt_ma.setText(x.getMa());
        java.awt.Image orImage = new ImageIcon(path + x.getAnh()).getImage();
        java.awt.Image resize = orImage.getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
        txt_anh1.setIcon(new ImageIcon(resize));
        hdhmodel.setSelectedItem(hdhs.searchById(x.getMaHDH()));
        hmodel.setSelectedItem(hs.searchById(x.getMaHang()));
        
    }
    
    public SanPham readForm(){
        SanPham x = new SanPham();
        x.setMa(txt_ma.getText());
        x.setTen(txt_ten.getText());
        x.setAnh(path1);
        x.setMota("x");
        HeDieuHanh b = (HeDieuHanh) cbo_hdh.getSelectedItem();
        Hang c = (Hang) cbo_hang.getSelectedItem();
        x.setMaHDH(b.getMa());
        x.setMaHang(c.getMa());
        x.setTrangThai("Còn Hàng");
        return x;
    }
    
     private void loadDataToDanhMuc() {
        hmodel.removeAllElements();
        HeDieuHanh hdh = (HeDieuHanh) cbo_hdh.getSelectedItem();
        ArrayList<Hang> li3 = hs.getAll(String.valueOf(hdh.getMa()));
        for (Hang x : li3) {
            hmodel.addElement(x);
        }
    }
}
